# Generated by Django 5.1.6 on 2025-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_notification_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
