# Generated by Django 5.1.6 on 2025-05-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_post_topics_post_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
