# Generated by Django 5.1.6 on 2025-05-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_picture_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
