# Generated by Django 5.1.7 on 2025-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_user_header_picture_blob_user_profile_picture_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
