# Generated by Django 5.1.6 on 2025-05-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_post_sentiment_post_sentiment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sentiment_score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='posts', to='data.topic'),
        ),
    ]
